/**
 * Event messages generated by controller.
 *
 * The events are generated by the most of the available methods in the controller. All
 * Message-Classes contain an attribute {@code mChange} of type
 * {@link org.noorganization.instalist.controller.event.Change}.
 */
package org.noorganization.instalist.controller.event;