/**
 * Event messages generated by presenter.
 *
 * The events are generated by the most of the available methods in the presenter. All
 * Message-Classes contain an attribute {@code mChange} of type
 * {@link org.noorganization.instalist.presenter.event.Change}.
 */
package org.noorganization.instalist.presenter.event;